/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum Language
{
  JAVA = 0,
  PYTHON = 1,
  MATLAB = 2,
  OCTAVE = 3,
  CPP = 4,
  CSHARP = 5,
}
