package at.enfilo.def.config.server.core;

import at.enfilo.def.config.server.api.IConfiguration;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * Created by mase on 18.02.2017.
 */
public class DEFRootConfiguration implements IConfiguration {

    public static final String PROPERTY_SERVER_HOLDER = "def-servers";
    public static final String PROPERTY_TICKET_SERVICE = "ticket-service";

    private String id = UUID.randomUUID().toString(); // If id value is not specified explicitly in config file, id will be generated by this line of code.

    private DEFServerHolderConfiguration serverHolderConfiguration = DEFServerHolderConfiguration.getDefault();

    private DEFTicketServiceConfiguration ticketServiceConfiguration = DEFTicketServiceConfiguration.getDefault();

    @JsonProperty
    public String getId() {
        return id;
    }

    @JsonProperty
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the def-servers-specific section of the configuration file.
     *
     * @return def-servers-specific configuration parameters.
     */
    @JsonProperty(PROPERTY_SERVER_HOLDER)
    public DEFServerHolderConfiguration getServerHolderConfiguration() {
        return serverHolderConfiguration;
    }

    /**
     * Sets the def-servers-specific section of the configuration file.
     */
    @JsonProperty(PROPERTY_SERVER_HOLDER)
    public void setServerHolderConfiguration(DEFServerHolderConfiguration serverHolderConfiguration) {
        this.serverHolderConfiguration = serverHolderConfiguration;
    }

    /**
     * Returns the ticket-service-specific section of the configuration file.
     *
     * @return ticket-service-specific configuration parameters.
     */
    @JsonProperty(PROPERTY_TICKET_SERVICE)
    public DEFTicketServiceConfiguration getTicketServiceConfiguration() {
        return ticketServiceConfiguration;
    }

    /**
     * Sets the ticket-service-specific section of the configuration file.
     */
    @JsonProperty(PROPERTY_TICKET_SERVICE)
    public void setTicketServiceConfiguration(DEFTicketServiceConfiguration ticketServiceConfiguration) {
        this.ticketServiceConfiguration = ticketServiceConfiguration;
    }
}
