/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package at.enfilo.def.communication.dto;


public enum Protocol implements org.apache.thrift.TEnum {
  DIRECT(0),
  REST(1),
  THRIFT_TCP(2),
  THRIFT_HTTP(3);

  private final int value;

  private Protocol(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Protocol findByValue(int value) { 
    switch (value) {
      case 0:
        return DIRECT;
      case 1:
        return REST;
      case 2:
        return THRIFT_TCP;
      case 3:
        return THRIFT_HTTP;
      default:
        return null;
    }
  }
}
