/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum RoutineType
{
  OBJECTIVE = 0,
  MAP = 1,
  STORE = 2,
  REDUCE = 3,
  CLIENT = 4,
}
