/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package at.enfilo.def.transfer.dto;


public enum Language implements org.apache.thrift.TEnum {
  JAVA(0),
  PYTHON(1),
  MATLAB(2),
  OCTAVE(3),
  CPP(4),
  CSHARP(5);

  private final int value;

  private Language(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Language findByValue(int value) { 
    switch (value) {
      case 0:
        return JAVA;
      case 1:
        return PYTHON;
      case 2:
        return MATLAB;
      case 3:
        return OCTAVE;
      case 4:
        return CPP;
      case 5:
        return CSHARP;
      default:
        return null;
    }
  }
}
