/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package at.enfilo.def.transfer.dto;


public enum NodeType implements org.apache.thrift.TEnum {
  WORKER(0),
  REDUCER(1),
  CLIENT(2);

  private final int value;

  private NodeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NodeType findByValue(int value) { 
    switch (value) {
      case 0:
        return WORKER;
      case 1:
        return REDUCER;
      case 2:
        return CLIENT;
      default:
        return null;
    }
  }
}
