/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RoutineCommunication_constants.h"

namespace at { namespace enfilo { namespace def { namespace routine { namespace api {

const RoutineCommunicationConstants g_RoutineCommunication_constants;

RoutineCommunicationConstants::RoutineCommunicationConstants() {
}

}}}}} // namespace

